###
#
# Greetings!
#
# This Makefile was generated by the Python package package package. If
# you don't know what that means, that's OK. This Makefile is mostly for
# the author of this package. If you are not the author you can ignore
# this file, or you can use it to call the setup.py commands that you
# are used to:
#
# * make build
# * make test
# * sudo make install
#
# If you are the module author, you can run `make help` to see all the
# commands that are available to you.
#
# This Makefile currently assumes that if you are the package author, that you
# are on some kind of Unix based system (or else you are kinda nuts, and
# probably shouldn't be using this thing in the first place! :)
#
# For more information on the package package package package, visit the
# Python Package Index here:
#
#     http://pypi.python.org/pypi/package/
#
# Cheers!
#
###

PACKAGE_BASE = $(MAKEFILE_LIST:%/Makefile=%)

.PHONY: setup default build test devtest install register sdist clean upload run

ALL_TESTS = $(shell echo tests/*.py)
ALL_DEV_TESTS = $(shell echo dev-tests/*.py)
PYTHON = python
SETUP_TARGETS = Makefile setup.py package

default: help

help::
	@cat $(PACKAGE_BASE)/MakeHelp.rst

setup:: $(SETUP_TARGETS)

$(SETUP_TARGETS)::
	cp -fr $(PACKAGE_BASE)/$@ ./

build test devtest install register sdist clean::
	$(PYTHON) setup.py $@

upload:: clean register
	$(PYTHON) setup.py sdist $@

tests:: $(ALL_TESTS)

$(ALL_TESTS) $(ALL_DEV_TESTS): run
	@$(PYTHON) -c 'print " Running test: $@ ".center(70, "-") + "\n"'
	@PYTHONPATH=. $(PYTHON) $@

clean::
	find . -name '*.pyc' | xargs rm
	rm -fr build dist MANIFEST *.egg-info
