#-----------------------------------------------------------------------------#
#
# Greetings!
#
# This Makefile was generated by the Python package package package. If
# you don't know what that means, that's OK. This Makefile is mostly for
# the author of this package. If you are not the author you can ignore
# this file, or you can use it to call the setup.py commands that you
# are used to:
#
# * make build
# * make test
# * sudo make install
#
# If you are the module author, you can run `make help` to see all the
# commands that are available to you.
#
# This Makefile currently assumes that, if you are the package author, that
# you are on some kind of Unix based system (or else you are kinda nuts, and
# probably shouldn't be using this thing in the first place! :)
#
# For more information on the Python package package package, visit the
# Python Package Index here:
#
#     http://pypi.python.org/pypi/package/
#
# Cheers!
#
#-----------------------------------------------------------------------------#

.PHONY: \
    default \
    help \
    setup \
    package-info \
    build \
    test \
    tests \
    devtest \
    install \
    register \
    sdist \
    clean \
    upload \
    run \
 

# This variable is hardcoded into the Makefile by initial setup.
# If you move package-py, you need to change this.
PACKAGE_BASE = $(MAKEFILE_LIST:%/Makefile=%)

PYTHON = python

PACKAGE_FILES = \
	package/__init__.py \
	package/errors.py \
	package/unittest.py \

SETUP_FILES = \
	setup.py \
	package/info.yaml \
	README.rst \
	LICENSE \
	CHANGES.yaml \

TESTS_FILES = \
	test_import.py \

SETUP_TARGETS = \
	Makefile \
	$(PACKAGE_FILES) \
	$(SETUP_FILES) \
	$(TESTS_FILES) \

UPGRADE_TARGETS = \
	Makefile \
	setup.py \
	$(PACKAGE_FILES) \

ALL_TESTS = $(shell echo tests/*.py)
ALL_DEV_TESTS = $(shell echo dev-tests/*.py)

#-----------------------------------------------------------------------------#
# package-py targets
#-----------------------------------------------------------------------------#
default:
	@echo "This is the Python package package package Makefile."
	@echo
	@echo "Run 'make help' for more information."

help::
	@cat $(PACKAGE_BASE)/help/make.txt

# This rule is disabled after initial setup.
setup: _setup $(SETUP_TARGETS) _fixup _next

_setup::
	@if [ -e "package" ]; then echo "Can't setup if 'package' directory exists."; else mkdir package; fi
	@if [ ! -e "tests" ]; then mkdir tests; fi

package-info::
	$(PYTHON) $(PACKAGE_BASE)/bin/make_package_info.py

upgrade: _not_for_me $(UPGRADE_TARGETS) _fixup package-info

_not_for_me::
	@if [ -e "help" ]; then echo "Don't do that here!!!"; exit 1; fi

_fixup::
	$(PYTHON) $(PACKAGE_BASE)/bin/fix_makefile.py "$(PACKAGE_BASE)"

_next::
	@cat $(PACKAGE_BASE)/help/next.txt

$(PACKAGE_FILES) Makefile::
	cp $(PACKAGE_BASE)/$@ $@

$(SETUP_FILES)::
	-cp -n $(PACKAGE_BASE)/setup/$@ $@

$(TESTS_FILES)::
	cp -n $(PACKAGE_BASE)/setup/tests/$@ tests/$@


#-----------------------------------------------------------------------------#
# setup.py targets
#-----------------------------------------------------------------------------#
register:: package-info

build test devtest install register sdist clean::
	$(PYTHON) setup.py $@

upload:: clean register
	$(PYTHON) setup.py sdist $@

tests:: $(ALL_TESTS)

$(ALL_TESTS) $(ALL_DEV_TESTS): run
	@$(PYTHON) -c 'print " Running test: $@ ".center(70, "-") + "\n"'
	@PYTHONPATH=. $(PYTHON) $@

clean::
	find . -name '*.pyc' | xargs rm
	rm -fr build dist MANIFEST *.egg-info
